### ISSUE TITLE
No releases or tags in this repository

### ISSUE THREAD

**Issue by frenck** [tuya/tuya-device-sharing-sdk#2]
Hi there 👋 

Looking at this repository, I don't see any releases or version tags. Therefore, as a developer, I have no idea what is in here and what has been published or not.

../Frenck

**Comment by shihuimiao** [comment]
sorry,This is the address of the released version
https://pypi.org/project/tuya-device-sharing-sdk

**Comment by frenck** [comment]
Sure, but that doesn't give any insights on GitHub and sources on the changes.

That said, I also don't see the release process happening here on GitHub, how do I know what is on PyPi is the same as in this repository?

../Frenck

**Comment by shihuimiao** [comment]
Sorry to have caused you such confusion. We will improve the content of the post in the future.

**Comment by make-all** [comment]
The current latest version in pypi is not matching what I see on https://github.com/tuya/tuya-device-sharing-sdk.  It seems to come from dev branch, and it isn't clear that it is an official release.
Is there any compatibility issue we should be concerned about moving from 0.1.9 to 0.2.0, since the most significant version number has changed?

**Comment by dotlambda** [comment]
There are still no tags on https://github.com/tuya/tuya-device-sharing-sdk/tags. It would be nice if you could add them.
